# Generated by Django 6.1 on 2026-10-02 20:06

import django.core.validators
import tables.models
import tenancy.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='token',
            field=tenancy.fields.ExactCharField(default=tables.models.table_token, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9]{6,64}\\Z', 'Usa entre 6 y 64 caracteres alfanuméricos.')]),
        ),
    ]
