# Generated by Django 6.1 on 2026-10-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_memoria_cupos_y_decisiones_del_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
