# Generated by Django 6.1 on 2026-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mysql_asistencia_abierta'),
        ('notifications', '0002_notification_low_stock_open_and_more'),
        ('tenancy', '0006_organization_suspension_by_billing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_low_stock_episode_unique',
        ),
        migrations.AddField(
            model_name='notification',
            name='low_stock_product',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('kind', 'inventory'), ('low_stock_open', True), ('res_model', 'catalog.Product')), then=models.F('res_id')), default=None, output_field=models.PositiveBigIntegerField(null=True)), output_field=models.PositiveBigIntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('restaurant', 'low_stock_product'), name='notification_low_stock_episode_unique'),
        ),
    ]
