# Generated by Django 6.1 on 2026-10-02 20:06

import tenancy.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_seed_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitgrant',
            name='key',
            field=tenancy.fields.ExactCharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='loyaltymove',
            name='key',
            field=tenancy.fields.ExactCharField(max_length=160),
        ),
    ]
