# Generated by Django 6.1 on 2026-10-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_unificar_telefonos_colombianos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
