# K4: galería de decoraciones por sede (PNG o WebP pequeños que insertan las plantillas de componente).
# Generated by Django 6.1 on 2026-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0026_borradores_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('content_type', models.CharField(max_length=20)),
                ('data', models.BinaryField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('restaurant_slug', 'venue_slug', 'slug'), name='uniq_menu_decoration')],
            },
        ),
    ]
