# Generated by Django 6.1 on 2026-10-02 20:06

import experience_app.models.diner
import tenancy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0030_alter_tablesession_table_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='one_unresolved_payment_per_visit',
        ),
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='one_unresolved_payment_per_reservation',
        ),
        migrations.RemoveConstraint(
            model_name='paymentgateway',
            name='one_active_gateway_per_venue',
        ),
        migrations.AlterField(
            model_name='diner',
            name='benefit_key',
            field=tenancy.fields.ExactCharField(default=experience_app.models.diner.new_key, max_length=64),
        ),
        migrations.AlterField(
            model_name='diner',
            name='key',
            field=tenancy.fields.ExactCharField(default=experience_app.models.diner.new_key, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dineraccount',
            name='registration_key',
            field=tenancy.fields.ExactCharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='reservation_token',
            field=tenancy.fields.ExactCharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='signupdiscountclaim',
            name='key',
            field=tenancy.fields.ExactCharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='table_token',
            field=tenancy.fields.ExactCharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='unresolved_reservation',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('status__in', ['CREATING', 'UNKNOWN', 'PENDING', 'APPROVED']), models.Q(('reservation_token', ''), _negated=True)), then=models.F('reservation_token')), default=None, output_field=tenancy.fields.ExactCharField(max_length=64, null=True)), output_field=tenancy.fields.ExactCharField(max_length=64, null=True)),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='unresolved_session',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('status__in', ['CREATING', 'UNKNOWN', 'PENDING', 'APPROVED'])), then=models.F('session_id')), default=None, output_field=models.UUIDField(null=True)), output_field=models.UUIDField(null=True)),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='active_venue',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('enabled', True)), then=models.F('venue_slug')), default=None, output_field=models.SlugField(null=True)), output_field=models.SlugField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('unresolved_session',), name='one_unresolved_payment_per_visit'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('unresolved_reservation',), name='one_unresolved_payment_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='paymentgateway',
            constraint=models.UniqueConstraint(fields=('restaurant_slug', 'active_venue'), name='one_active_gateway_per_venue'),
        ),
    ]
