# Generated by Django 6.1 on 2026-10-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historial_seguridad_soporte_y_tarifa'),
        ('experience_app', '0031_mysql_tokens_y_unicos_sin_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='checks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='verify_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='PaymentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('code_expires', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('grant_hash', models.CharField(blank=True, max_length=64)),
                ('grant_expires', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_access', to='accounts.account')),
            ],
        ),
    ]
