# Generated by Django 6.1 on 2026-10-02 20:06

import reservations.models
import tenancy.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_reservation_time_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pay_token',
            field=tenancy.fields.ExactCharField(default=reservations.models.pay_token, max_length=32, unique=True),
        ),
    ]
