# Generated by Django 6.1 on 2026-10-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_domicilios_cobertura_direcciones_y_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchusage',
            name='reverses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
