# Generated by Django 6.1 on 2026-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_lecturas_de_direccion_del_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchusage',
            name='suggests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
