# Generated by Django 6.1 on 2026-10-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_sugerencias_de_direccion'),
        ('tenancy', '0013_tono_del_asistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('kind', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'day', 'kind'), name='delivery_maps_usage_unico')],
            },
        ),
    ]
