# Generated by Django 6.1 on 2026-10-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_consultas_a_google_maps'),
        ('experience_app', '0031_mysql_tokens_y_unicos_sin_condicion'),
        ('tenancy', '0014_horario_de_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationdelivery',
            name='cart',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.restaurant'),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_app.tablesession'),
        ),
        migrations.AddField(
            model_name='conversationdelivery',
            name='step',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='fee_mode',
            field=models.CharField(choices=[('distance', 'distance'), ('flat', 'flat'), ('free', 'free')], default='distance', max_length=10),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='flat_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='free_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sessiondelivery',
            name='marked_lines',
            field=models.JSONField(default=list),
        ),
    ]
