# Generated by Django 6.1 on 2026-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_notify_prefs'),
        ('tenancy', '0006_organization_suspension_by_billing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='one_open_attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='open_account',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('check_out__isnull', True)), then=models.F('account_id')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('open_account',), name='one_open_attendance'),
        ),
    ]
