# Generated by Django 6.1 on 2026-10-02 20:06

import tenancy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mysql_asistencia_abierta'),
        ('sales', '0006_seed_online_payment'),
        ('tenancy', '0006_organization_suspension_by_billing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashshift',
            name='one_open_cash_shift',
        ),
        migrations.AddField(
            model_name='cashshift',
            name='open_restaurant',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('state', 'open')), then=models.F('restaurant_id')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_key',
            field=tenancy.fields.ExactCharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(fields=('open_restaurant',), name='one_open_cash_shift'),
        ),
    ]
