# Generated by Django 6.1 on 2026-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_historial_seguridad_soporte_y_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='assistant_tone',
            field=models.CharField(default='neutro', max_length=20),
        ),
    ]
