# Generated by Django 6.1 on 2026-10-02 20:06

import tenancy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mysql_asistencia_abierta'),
        ('catalog', '0002_seed_organizations'),
        ('inventory', '0002_alter_stockmove_account'),
        ('tenancy', '0006_organization_suspension_by_billing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaserequest',
            name='purchase_one_supplier_draft',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='draft_supplier',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('state', 'draft')), then=models.F('supplier_id')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='request_key',
            field=tenancy.fields.ExactCharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('restaurant', 'draft_supplier'), name='purchase_one_supplier_draft'),
        ),
    ]
