# Generated by Django 6.1 on 2026-10-02 20:06

import tenancy.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='request_key',
            field=tenancy.fields.ExactCharField(max_length=80),
        ),
    ]
